[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.72", features = ["Crypto"] }
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"