[package]
name = "arlekin-client"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3", features = ["Crypto"] }
yew.workspace = true
yew-router.workspace = true
