name: Main

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - release-*
      - dev-*

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Instal stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache crates
        uses: Swatinem/rust-cache@v2
      - name: Install Taplo
        run: cargo install --locked taplo-cli
      - name: Format
        run: |
          cargo fmt --all --check
          taplo fmt --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Instal stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache crates
        uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --benches --tests -- -D warnings
      - name: Rustdoc
        run: cargo doc --all-features

  doctest:
    name: Doctest
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Instal stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache crates
        uses: Swatinem/rust-cache@v2
      - name: Test doc
        run: cargo test --all-features --doc

  feature-combinations:
    name: Feature combinations
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Instal stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache crates
        uses: Swatinem/rust-cache@v2
      - name: Install Cargo Hack
        run: cargo install cargo-hack
      - name: Check feature combinations
        run: cargo hack check --feature-powerset
        env:
          RUSTFLAGS: -Aunused -Dwarnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Instal stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache crates
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
